= https://isaqb.org[iSAQB] Advanced Level Curriculum AGILA

:toc:
:toc-placement!:

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Status
image:https://github.com/isaqb-org/curriculum-agila/actions/workflows/build_main.yml/badge.svg?branch=main["CI – Releases and Main"]
image:https://img.shields.io/github/last-commit/isaqb-org/curriculum-agila/main.svg["Last commit"]
image:https://img.shields.io/github/contributors/isaqb-org/curriculum-agila.svg["Contributors",link="https://github.com/isaqb-org/curriculum-agila/graphs/contributors"]
image:https://img.shields.io/github/issues/isaqb-org/curriculum-agila.svg["Issues",link="https://github.com/isaqb-org/curriculum-agila/issues"]
image:https://img.shields.io/github/issues-closed/isaqb-org/curriculum-agila.svg["Issues closed",link="https://github.com/isaqb-org/curriculum-agila/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+"]


This is <<copyrighted,copyrighted work>>.

== Content
This repository contains the curriculum of the iSAQB® Advanced Level module AGILA in AsciiDoc.

toc::[]

== How to contribute or participate
Create an issue, a merge- or pull-request

== How to check out and build

. Clone the repository including the submodules:
+
--
[source,shell]
----
Via SSH:
git clone git@github.com:isaqb-org/curriculum-agila.git --recursive

Via HTTPS:
git clone https://github.com/isaqb-org/curriculum-agila.git --recursive
----
--

You build the output documents with `./gradlew buildDocs`. Prerequisite: You need a Java Runtime(tm) (17 or higher) installed.

== Additional translations/languages
include::docs-ext/EXTERNAL_DOCUMENTS_README.adoc[]

== Maintainers

This repository is currently maintained by Stefan Toth.
It was forked from https://github.com/isaqb-org/advanced-template,
so the contributors of that project basically contributed to this one, too.


[[copyrighted]]
== Licensing and Copyright

include::license-copyright/LICENSE.adoc[]
