=== {learning-goals}


// tag::DE[]
[[LZ-6-1]]
==== LZ 6-1: Beispiele für Entscheidungsverfahren in agilen Projekten kennen und nachvollziehen
Teilnehmer sollen an mindestens zwei Beispielen nachvollziehen können, wie agile Projekte unterschiedlicher Größe Architekturentscheidungen treffen und kommunizieren. Dazu sollten in Schulungen die relevanten Meetings, Rollen und Verantwortlichkeiten beschrieben werden, sowie die konkrete Einbettung in den agilen Prozess des jeweiligen Projekts deutlich werden.

[[LZ-6-2]]
==== LZ 6-2: Beispiele für agil ausgeprägte Architekturanforderungen kennen und nachvollziehen
- Teilnehmer sollen mindestens ein Beispiel für die Formulierung von Architekturanforderungen und deren Einbettung in agile Anforderungsartefakte (wie Stories oder Backlogs) nachvollziehen können.
- Teilnehmer sollen Beispiele nachvollziehen, die gemeinsame Arbeit an Architekturanforderungen in realen Projekten zeigen (Grooming, Planning etc.).

[[LZ-6-3]]
==== LZ 6-3: Physische Ausprägungen agiler Kommunikationsansätze kennen
Teilnehmer sollen in Beispielen sehen und nachvollziehen können wie agile Projekte Architekturinformationen und -entscheidungen kommunizieren (Fotos von informativen Arbeitsplätzen, Layouts von Informationsradiatoren etc.).

[[LZ-6-4]]
==== LZ 6-4: Verschiebung von Architekturentscheidungen nachvollziehen können
Teilnehmer sollen in einem realen Beispiel die Verschiebung von Architekturentscheidungen kennenlernen und nachvollziehen können.

[[LZ-6-5]]
==== LZ 6-5: Beispiele für agil organisierte Architekturgruppen kennen und nachvollziehen
Teilnehmer sollen in mindestens zwei realen Beispielen die Organisation von Architekturcommunities oder -gilden kennenlernen und nachvollziehen können, sowie die Aktivitäten und Techniken kennenlernen die Unternehmen einsetzen, um diese Gruppen zu etablieren und aktiv zu halten.


// end::DE[]

// tag::EN[]
[[LG-6-1]]
==== LG 6-1: Being familiar with and understanding examples for decision-making procedures in agile projects
Based on at least two examples, participants should be able to understand how agile projects of different sizes make and communicate architecture decisions. For this purpose, the relevant meetings, roles and responsibilities should be described in courses, and the specific embedding into the agile process of the respective project should be made clear.

[[LG-6-2]]
==== LG 6-2: Being familiar with and understanding examples for agile architecture requirements
- Participants should be able to understand at least one example for the formulation of architecture requirements and their embedding into agile requirements artefacts (such as stories or backlogs).
- Participants should understand examples of joint work on architecture requirements in real projects (grooming, planning etc.).

[[LG-6-3]]
==== LG 6-3: Being familiar with physical characteristics of agile communication concepts
Participants should be able to see and understand, in examples, how agile projects communicate architecture information and decisions (photos of informative workplaces, layouts of information radiators etc.).

[[LG-6-4]]
==== LG 6-4: Being able to understand the postponement of architecture decisions
Based on a real example, participants should become familiar with and understand the postponement of architecture decisions.

[[LG-6-5]]
==== LG 6-5: Being familiar with and understanding examples of agilely organised architecture groups
In at least two real examples, participants should become familiar with and understand the organisation of architecture communities or guilds, and become familiar with the activities and techniques used by companies to establish these groups and keep them active.

// end::EN[]

// tag::REMARK[]
[NOTE]
====
Die einzelnen Lernziele müssen nicht als einfache Aufzählungen mit Unterpunkten aufgeführt werden, sondern können auch gerne in ganzen Sätzen formuliert werden, welche die einzelnen Punkte (sofern möglich) integrieren.
====
// end::REMARK[]
