// tag::DE[]
|===
| Dauer: 240 Min. |
|===

=== Begriffe und Konzepte
- Zusammenarbeit mit Kunden und anderen Stakeholdern: Kommunikationsebenen, Architekturprobleme zielgruppenorientiert ausdrücken, Anforderungen und Wünsche in Architekturkonzepte übersetzen
- Qualitätsanforderungen in agilen Prozessen
- Technische Schulden
- Architektonische Risiken inkl. Erhebung
- Anforderungspflege, Grooming, Schätzung und Priorisierung von Architekturanforderungen
- Dringlichkeit von Architekturthemen und der letzte vernünftige Moment


// end::DE[]

// tag::EN[]
|===
| Duration: 240 min |
|===

=== Terms and Principles
- Collaboration with customers and other stakeholders: Explanation of communication levels and architecture problems appropriately for specific target groups, translation of requirements and wishes into architecture concepts
- Quality requirements in agile processes
- Technical debt
- Architectural risks incl. their determination
- Requirements management; grooming, evaluation and prioritisation of architecture requirements
- Urgency of architecture issues and the last responsible moment.

// end::EN[]




