=== {learning-goals}

// tag::DE[]
[[LZ-1-1]]
==== LZ 1-1: Die Bedeutung agiler Ideen für Architekturarbeit kennen und erläutern können
- Definitionen von Softwarearchitektur kennen:
    * Welche Definitionen passen zu agilen Umfeldern?
    * Wie grenzt sich Architektur zu Design ab?
- Agile Weltsicht und Prinzipien kennen:
    * Cynefin-Framework und Komplexität als Einfluss auf Vergehensmodelle
    * Relevante Wertpaare und Prinzipien des agilen Manifests (z. B. "Responding to Change over Following a Plan")
    * Typische Fehlanwendungen (z. B. Cargo Cult Agilität) erkennen und kritisch reflektieren.
- Architektur und Agilität im Zusammenspiel verstehen
    * Synergien von Architektur und Agilität
    * Einflüsse von Scrum, Lean und agilen Denkmodellen auf Architekturentscheidungen 
    * Grundhaltung agiler Architekturarbeit: frühes Feedback, kollaborative Entscheidungsfindung, evolutionäre Weiterentwicklung über Hypothesen

[[LZ-1-2]]
==== LZ 1-2: Aufgaben der Architekturentwicklung und deren Abwandlung im agilen Umfeld kennen
- Klärung wie die folgenden, im CPSA-Foundation-Lehrplan definierten, Aufgaben
der Architekturentwicklung im agilen Umfeld wahrgenommen werden:
    * Anforderungen und Randbedingungen klären, hinterfragen und bei Bedarf verfeinern.
    * Strukturentscheidungen hinsichtlich Systemzerlegung und Bausteinstruktur treffen, dabei Abhängigkeiten und Schnittstellen zwischen den Bausteinen festlegen.
    * Übergreifende technische Konzepte entscheiden (beispielsweise Persistenz, Kommunikation, GUI) und bei Bedarf umsetzen.
    * Software-Architektur auf Basis von Sichten, Architekturmustern und technischen Konzepten kommunizieren und dokumentieren.
    * Umsetzung und Implementierung der Architektur begleiten, Rückmeldungen der beteiligten Stakeholder bei Bedarf in die Architektur einarbeiten, Konsistenz von Quellcode und Software-Architektur prüfen und sicherstellen.
    * Software-Architektur bewerten, insbesondere hinsichtlich Risiken bezüglich der geforderten Qualitätsmerkmale.
    * Wenig Änderung an den Themen der Architekturarbeit, jedoch häufig Anpassung der Arbeitsweise bei der Bearbeitung von Architekturfragen (Aufgabenverteilung, Entscheidungsfindung, Ergebniskommunikation etc.).
    * Mapping der wichtigsten Veränderungen auf die Inhalte dieses Lehrplans.

[[LZ-1-3]]
==== LZ 1-3: Architekturaufwand angemessen an Problemstellung und Projekt ausrichten können
- Spannungsfeld zwischen schneller Reaktionsfähigkeit und guter Planbarkeit bzw. Steuerbarkeit.
    * Im negativen Extrem: Spannungsfeld zwischen geringer Reaktionsfähigkeit (Starre) und schwerer Beherrschbarkeit (Chaos)
- Gerade genug Architekturarbeit und unterstützende Konzepte - Arbeitseinsatz auf relevante Probleme beschränken:
    * Kriterien zur Bewertung von Architekturrelevanz und zum gezielten Einsatz architektonischer Aktivitäten
    * Prinzipien aus Lean (z. B. Waste-Reduktion) auf Architekturarbeit
    * Fokussierung von Kommunikation

// end::DE[]

// tag::EN[]
[[LG-1-1]]
==== LG 1-1: Knowing and being able to explain the significance of agile ideas for architecture work
- Knowing definitions of software architecture:
    * Which definitions are suitable for agile environments?
    * How is architecture distinguished from design?
- Knowing the agile world view and principles:
    * Cynefin framework and complexity as a factor influencing process models
    * Relevant value pairs and principles of the Agile Manifesto (e.g., “Responding to change over following a plan”)
    * Recognizing and critically reflecting on typical misapplications (e.g., Cargo Cult Agility)
- Understanding the interaction between architecture and agility:
    * Synergies between architecture and agility
    * Influences of Scrum, Lean, and agile thinking models on architectural decisions
    * Core mindset of agile architecture work: early feedback, collaborative decision-making, evolutionary development through hypotheses

[[LG-1-2]]
==== LG 1-2: Knowing the tasks involved in architecture development and how they are modified in the agile environment
- Clarification of how the following architecture development tasks defined in the CPSA Foundation Curriculum are perceived in the agile environment:
    * Clarification, scrutiny and where necessary refinement of requirements and conditions/constraints.
    * Making structure decisions in respect of system decomposition and module structure, and defining dependencies and interfaces between the modules.
    * Defining and where necessary implementing general technical concepts (for example persistence, communication, GUI).
    * Communicating and documenting software architecture based on views, architectural patterns and technical concepts.
    * Supporting the realisation and implementation of the architecture, where necessary incorporation of feedback from the involved stakeholders into the architecture, and checking and ensuring consistency of the source code and the software architecture.
    * Reviewing software architectures, in particular in terms of risks in respect of the specified quality criteria.
    * Little change to the topics covered by architecture work, but often changes in the methods used when addressing architecture issues (allocation of tasks, decision making, communication of the results etc.).
    * Mapping of the most important changes to the contents of this curriculum.

[[LG-1-3]]
==== LG 1-3: Being able to appropriately align architecture work to the specific problem and project
- Tension between rapid responsiveness and sufficient planning or manageability:
    * In the extreme case: tension between low responsiveness (rigidity) and poor controllability (chaos)
- Just enough architecture work and supporting concepts – limiting effort to relevant problems:
    * Criteria for evaluating architectural relevance and targeted application of architectural activities
    * Applying Lean principles (e.g., waste reduction) to architectural work
    * Focusing communication

// end::EN[]


